{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "executing high level function\n",
      "high level function begining\n",
      "\n",
      "\n",
      "Step: 1/2\n",
      "____________________________\n",
      "attempting to divide the given numbers: 5/1\n",
      "Answer to division: 5.0\n",
      "\n",
      "\n",
      "Step: 2/2\n",
      "____________________________\n",
      "Fail: 420\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "Retrying 1/3:\n",
      "Fail: 490\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "Retrying 2/3:\n",
      "Fail: 506\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "Retrying 3/3:\n",
      "Fail: 458\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "max amount of retries reached: 3/3\n",
      "AWS S3 server appears to be down\n",
      "Try again in a short amount of time\n",
      "\n",
      "High level function did not complete\n",
      "Retrying entire app flow\n",
      "Cleaning up temporary files\n",
      "\n",
      "\n",
      "\n",
      "Retrying 1/3:\n",
      "high level function begining\n",
      "\n",
      "\n",
      "Step: 1/2\n",
      "____________________________\n",
      "attempting to divide the given numbers: 5/1\n",
      "Answer to division: 5.0\n",
      "\n",
      "\n",
      "Step: 2/2\n",
      "____________________________\n",
      "Fail: 546\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "Retrying 1/3:\n",
      "Fail: 410\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "Retrying 2/3:\n",
      "Fail: 439\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "Retrying 3/3:\n",
      "Fail: 490\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "max amount of retries reached: 3/3\n",
      "AWS S3 server appears to be down\n",
      "Try again in a short amount of time\n",
      "\n",
      "High level function did not complete\n",
      "Retrying entire app flow\n",
      "Cleaning up temporary files\n",
      "\n",
      "\n",
      "\n",
      "Retrying 2/3:\n",
      "high level function begining\n",
      "\n",
      "\n",
      "Step: 1/2\n",
      "____________________________\n",
      "attempting to divide the given numbers: 5/1\n",
      "Answer to division: 5.0\n",
      "\n",
      "\n",
      "Step: 2/2\n",
      "____________________________\n",
      "Fail: 471\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "Retrying 1/3:\n",
      "Fail: 470\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "Retrying 2/3:\n",
      "Fail: 484\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "Retrying 3/3:\n",
      "Fail: 491\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "max amount of retries reached: 3/3\n",
      "AWS S3 server appears to be down\n",
      "Try again in a short amount of time\n",
      "\n",
      "High level function did not complete\n",
      "Retrying entire app flow\n",
      "Cleaning up temporary files\n",
      "\n",
      "\n",
      "\n",
      "Retrying 3/3:\n",
      "high level function begining\n",
      "\n",
      "\n",
      "Step: 1/2\n",
      "____________________________\n",
      "attempting to divide the given numbers: 5/1\n",
      "Answer to division: 5.0\n",
      "\n",
      "\n",
      "Step: 2/2\n",
      "____________________________\n",
      "Fail: 512\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "Retrying 1/3:\n",
      "Fail: 446\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "Retrying 2/3:\n",
      "Fail: 506\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "Retrying 3/3:\n",
      "Fail: 496\n",
      "Error: AWS S3 server is likely down\n",
      "\n",
      "max amount of retries reached: 3/3\n",
      "AWS S3 server appears to be down\n",
      "Try again in a short amount of time\n",
      "\n",
      "High level function did not complete\n",
      "Retrying entire app flow\n",
      "Cleaning up temporary files\n",
      "\n",
      "\n",
      "\n",
      "max amount of retries reached: 3/3\n"
     ]
    },
    {
     "ename": "S3ApiError",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mS3ApiError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\ggomp\\OneDrive\\Documents\\VSCode Repos from Github\\Python\\Python Core\\Retry_Functionality.ipynb Cell 1'\u001b[0m in \u001b[0;36m<cell line: 108>\u001b[1;34m()\u001b[0m\n\u001b[0;32m    <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=104'>105</a>\u001b[0m         \u001b[39mprint\u001b[39m(\u001b[39m'\u001b[39m\u001b[39mCleaning up temporary files\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m'\u001b[39m)\n\u001b[0;32m    <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=106'>107</a>\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m'\u001b[39m\u001b[39mexecuting high level function\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[1;32m--> <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=107'>108</a>\u001b[0m high_level_function()\n",
      "\u001b[1;32mc:\\Users\\ggomp\\OneDrive\\Documents\\VSCode Repos from Github\\Python\\Python Core\\Retry_Functionality.ipynb Cell 1'\u001b[0m in \u001b[0;36mretry.<locals>.retry_wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=18'>19</a>\u001b[0m \u001b[39mwhile\u001b[39;00m counter \u001b[39m<\u001b[39m\u001b[39m=\u001b[39m retry_count:\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=19'>20</a>\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m---> <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=20'>21</a>\u001b[0m         \u001b[39mreturn\u001b[39;00m function_name(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=22'>23</a>\u001b[0m     \u001b[39mexcept\u001b[39;00m S3ApiError \u001b[39mas\u001b[39;00m error:\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=23'>24</a>\u001b[0m         counter \u001b[39m+\u001b[39m\u001b[39m=\u001b[39m \u001b[39m1\u001b[39m\n",
      "\u001b[1;32mc:\\Users\\ggomp\\OneDrive\\Documents\\VSCode Repos from Github\\Python\\Python Core\\Retry_Functionality.ipynb Cell 1'\u001b[0m in \u001b[0;36mhigh_level_function\u001b[1;34m()\u001b[0m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=82'>83</a>\u001b[0m deployer\u001b[39m.\u001b[39mcodecommit_api_call(\u001b[39m5\u001b[39m,\u001b[39m1\u001b[39m)\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=84'>85</a>\u001b[0m deployer\u001b[39m.\u001b[39mnext_step_log_message()\n\u001b[1;32m---> <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=85'>86</a>\u001b[0m deployer\u001b[39m.\u001b[39;49ms3_api_call(\u001b[39m400\u001b[39;49m,\u001b[39m550\u001b[39;49m)\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=87'>88</a>\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m'\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m___________________________________________\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=88'>89</a>\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m'\u001b[39m\u001b[39mhigh level function completed successfully\u001b[39m\u001b[39m'\u001b[39m)\n",
      "\u001b[1;32mc:\\Users\\ggomp\\OneDrive\\Documents\\VSCode Repos from Github\\Python\\Python Core\\Retry_Functionality.ipynb Cell 1'\u001b[0m in \u001b[0;36mretry.<locals>.retry_wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=18'>19</a>\u001b[0m \u001b[39mwhile\u001b[39;00m counter \u001b[39m<\u001b[39m\u001b[39m=\u001b[39m retry_count:\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=19'>20</a>\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m---> <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=20'>21</a>\u001b[0m         \u001b[39mreturn\u001b[39;00m function_name(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=22'>23</a>\u001b[0m     \u001b[39mexcept\u001b[39;00m S3ApiError \u001b[39mas\u001b[39;00m error:\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=23'>24</a>\u001b[0m         counter \u001b[39m+\u001b[39m\u001b[39m=\u001b[39m \u001b[39m1\u001b[39m\n",
      "\u001b[1;32mc:\\Users\\ggomp\\OneDrive\\Documents\\VSCode Repos from Github\\Python\\Python Core\\Retry_Functionality.ipynb Cell 1'\u001b[0m in \u001b[0;36mDeployer.s3_api_call\u001b[1;34m(self, first_number, last_number)\u001b[0m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=69'>70</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=70'>71</a>\u001b[0m     \u001b[39mprint\u001b[39m(\u001b[39mf\u001b[39m\u001b[39m'\u001b[39m\u001b[39mFail: \u001b[39m\u001b[39m{\u001b[39;00mresponse_code\u001b[39m}\u001b[39;00m\u001b[39m'\u001b[39m)\n\u001b[1;32m---> <a href='vscode-notebook-cell:/c%3A/Users/ggomp/OneDrive/Documents/VSCode%20Repos%20from%20Github/Python/Python%20Core/Retry_Functionality.ipynb#ch0000000?line=71'>72</a>\u001b[0m     \u001b[39mraise\u001b[39;00m S3ApiError()\n",
      "\u001b[1;31mS3ApiError\u001b[0m: "
     ]
    }
   ],
   "source": [
    "import random\n",
    "import time\n",
    "import traceback\n",
    "\n",
    "# 1. write this for an api call that can return 200 or any other error code\n",
    "# 2. write this for an api call that returns an actual error\n",
    "\n",
    "class CodeCommitApiError(Exception):\n",
    "    def __init__(self):\n",
    "        print(f'Error: AWS CodeCommit server is likely down, try again in a short amount of time')\n",
    "\n",
    "class S3ApiError(Exception):\n",
    "    def __init__(self):\n",
    "        print(f'Error: AWS S3 server is likely down\\n')\n",
    "\n",
    "def retry(function_name, retry_count=3):\n",
    "        def retry_wrapper(*args, **kwargs):\n",
    "            counter = 0\n",
    "            while counter <= retry_count:\n",
    "                try:\n",
    "                    return function_name(*args, **kwargs)\n",
    "\n",
    "                except S3ApiError as error:\n",
    "                    counter += 1\n",
    "                    if counter <= retry_count:\n",
    "                        print(f\"Retrying {counter}/{retry_count}:\")\n",
    "                    else:\n",
    "                        print(f\"max amount of retries reached: {counter-1}/{retry_count}\")\n",
    "                        raise\n",
    "                    time.sleep(.1)\n",
    "                    \n",
    "                except Exception as error:\n",
    "                    print(traceback.format_exc())\n",
    "                    counter += 1\n",
    "                    if counter <= retry_count:\n",
    "                        print(f\"Retrying {counter}/{retry_count}:\")\n",
    "                    else:\n",
    "                        print(f\"max amount of retries reached: {counter-1}/{retry_count}\")\n",
    "                        raise CodeCommitApiError()\n",
    "                    time.sleep(.1)\n",
    "        return retry_wrapper\n",
    "\n",
    "\n",
    "class Deployer():\n",
    "    def __init__(self):\n",
    "        self.STEP_COUNT = 0\n",
    "        self.STEP_MAX = 2 \n",
    "\n",
    "    def next_step_log_message(self):\n",
    "            self.STEP_MAX = 2\n",
    "            self.STEP_COUNT += 1\n",
    "            print(f'\\n')\n",
    "            print(f'Step: {self.STEP_COUNT}/{self.STEP_MAX}')\n",
    "            print(f'____________________________')\n",
    "    \n",
    "    @retry\n",
    "    def codecommit_api_call(self, first_number, last_number):\n",
    "        \"\"\"case where api returns an actual error\"\"\"\n",
    "        print(f'attempting to divide the given numbers: {first_number}/{last_number}')\n",
    "        print(f'Answer to division: {first_number/last_number}')\n",
    "    \n",
    "    @retry\n",
    "    def s3_api_call(self, first_number, last_number):\n",
    "        \"\"\" case where api call can return 200 or anything else \"\"\"\n",
    "        # api_call_response = api.api_call(arg1, arg 2)\n",
    "        response_code = random.randint(first_number, last_number)\n",
    "        if response_code == 200:\n",
    "            print(f'Success: {response_code}')\n",
    "            return response_code\n",
    "        else:\n",
    "            print(f'Fail: {response_code}')\n",
    "            raise S3ApiError()\n",
    "    \n",
    "\n",
    "# now this is the \"high level function\", which is sitting in another file\n",
    "# ________________________________________________________________\n",
    "@retry\n",
    "def high_level_function():\n",
    "    print('high level function begining')\n",
    "    deployer = Deployer()\n",
    "    try:\n",
    "        deployer.next_step_log_message()\n",
    "        deployer.codecommit_api_call(5,1)\n",
    "        \n",
    "        deployer.next_step_log_message()\n",
    "        deployer.s3_api_call(400,550)\n",
    "        \n",
    "        print('\\n___________________________________________')\n",
    "        print('high level function completed successfully')\n",
    "    except CodeCommitApiError:\n",
    "        print('\\nHigh level function did not complete')\n",
    "        print('Retrying entire app flow')\n",
    "        raise\n",
    "    except S3ApiError:\n",
    "        print('AWS S3 server appears to be down')\n",
    "        print(f\"Try again in a short amount of time\")\n",
    "        print('\\nHigh level function did not complete')\n",
    "        print('Retrying entire app flow')\n",
    "        raise\n",
    "    except Exception:\n",
    "        print(traceback.format_exc())\n",
    "        print('\\nHigh level function did not complete')\n",
    "        print('Retrying entire app flow')\n",
    "    finally:\n",
    "        print('Cleaning up temporary files\\n\\n\\n')\n",
    "\n",
    "print('executing high level function')\n",
    "high_level_function()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "81794d4967e6c3204c66dcd87b604927b115b27c00565d3d43f05ba2f3a2cb0d"
  },
  "kernelspec": {
   "display_name": "Python 3.9.7 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
